input {
  file {
    path => "/var/log/nginx/access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    tags => ["nginx-access", "logstash"]
  }
}

filter {
  grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
  }
  
  date {
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    target => "@timestamp"
  }
  
  mutate {
    rename => { "clientip" => "client_ip" }
    rename => { "response" => "response_code" }
    convert => { "response_code" => "integer" }
    convert => { "bytes" => "integer" }
  }
  
  useragent {
    source => "agent"
    target => "user_agent"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx-logs-logstash-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
